#include "aes.h"
#include "cmac.h"

#include "utils.h"

#define ACCENTCOLOR "\033[1;36m"
#define DEFAULT "\033[0m"

void run(char* argv[]);

int main(int argc, char* argv[])
{
    run(argv);

    return 0;
}

void run(char* argv[])
{
    unsigned char key[] = {
        0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF
    };

    // unsigned char message[] = 
    // {
    //     // Random string generated by `openssl rand -hex 32`
    //     "93AB811B842ABEE9D0588162ED6A06FD"
    // };
    unsigned char message[] = {
        0x93,0xAB,0x81,0x1B,
        0x84,0x2A,0xBE,0xE9,
        0xD0,0x58,0x81,0x62,
        0xED,0x6A,0x06,0xFD
    };

    unsigned char out[16];

    printf("%sInput message%s\n", ACCENTCOLOR, DEFAULT);
    printf("%s\n", message);
    printf("%sKey%s\n", ACCENTCOLOR, DEFAULT);
    print_bytes(key, 16);
    aes_cmac(message, sizeof(message), (unsigned char*)out, key);
    printf("%sAES-128-CMAC Result%s\n", ACCENTCOLOR, DEFAULT);
    print_bytes(out, 16);
}



